import "../globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { LangProvider } from "@/context/LangContext";
import { getPlainDictionary } from "@/utils/translations";
import { Locale } from "@/i18n.config";

import LanguageSwitcher from "@/components/LanguageSwitcher";
import MainMenu from "@/components/MainMenu";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params,
  children,
}: Readonly<{
  params: Promise<{lang: string}>,
  children: React.ReactNode;
}>) {
  const { lang } = await params as {lang: Locale};

  const translationDict = await getPlainDictionary(lang);

  return (
    <html
      lang={lang}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/*  grid grid-rows-[auto_1fr_auto] */}
      <body className="min-h-screen flex flex-col bg-slate-50/30 m-0 p-0">
        <LangProvider initialLang={lang} initialDict={translationDict}>
          <MainMenu>
            <LanguageSwitcher />
          </MainMenu>

          <main className="w-full">{children}</main>

          <Footer />
        </LangProvider>
      </body>
    </html>
  );
}
